name: Update Telegram CIDR for Surge

on:
  schedule:
    - cron: "0 2 * * *"   # 每日 UTC+0 02:00 執行 (台灣時間 10:00)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install requests
        run: pip install requests

      - name: Run conversion script
        run: python scripts/tg_cidr_list.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add rules/tg.list
          git commit -m "Update Telegram CIDR list [auto]" || echo "No changes"
          git push
